 List doctorData = [
  {
    "name": "Dr.David Kemp",
    "type": "Heart Surgeon",
    "rating": 4.5,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "satisfaction": 85.2,
    "isfavourite": true,
    "image": "assets/images/doctor1.jpg",
    "description": "A doctor can be found in several settings, including public health organization, group practices and hospitals. They have some of the most diverse and challenging careers available and are part of a universally well-respected profession.",
  },
  {
    "name": "Dr.katthy Mathews",
    "type": "Neurology",
    "rating": 3.5,
    "goodReviews": 93.2,
    "totalScore": 72.2,
    "satisfaction": 89.2,
    "isfavourite": false,
    "image": "assets/images/doctor2.jpg",
    "description": "A doctor can be found in several settings, including public health organization, group practices and hospitals. They have some of the most diverse and challenging careers available and are part of a universally well-respected profession.",
  },
  {
    "name": "DR. Amal",
    "type": "Cardio Surgeon",
    "rating": 2.5,
    "goodReviews": 88.2,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "isfavourite": false,
    "image": "assets/images/doctor3.jpg",
    "description": "A doctor can be found in several settings, including public health organization, group practices and hospitals. They have some of the most diverse and challenging careers available and are part of a universally well-respected profession.",
  },
  {
    "name": "Dr. Sara",
    "type": "Heart Surgeon",
    "rating": 1.5,
    "goodReviews": 12.2,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "isfavourite": true,
    "image": "assets/images/doctor4.jpg",
    "description": "A doctor can be found in several settings, including public health organization, group practices and hospitals. They have some of the most diverse and challenging careers available and are part of a universally well-respected profession.",
  }
];

