List DoctorMapList = [
  {
    "name": " Dr. Hadeel",
    "type": " Heart Surgeon",
    "rating": 4.9,
    "goodReviews": 79.2,
    "totalScore": 93.2,
    "satisfaction": 85.2,
    "isfavourite": true,
    "image": "assets/images/doctor1.jpg",
    "description": "A doctor can be found in several settings",
  },
  {
    "name": " Dr.Dema ",
    "type": " General Dentist",
    "rating": 4.9,
    "goodReviews": 93.2,
    "totalScore": 72.2,
    "satisfaction": 89.2,
    "isfavourite": false,
    "image": "assets/images/doctor2.jpg",
    "description": "A doctor can be found in several settings",
  },
  {
    "name": " DR. Omar",
    "type": " Neurosurgery",
    "rating": 4.9,
    "goodReviews": 88.2,
    "totalScore": 93.94,
    "satisfaction": 78.2,
    "isfavourite": false,
    "image": "assets/images/doctor3.jpg",
    "description": "A doctor can be found in several settings, ",
  },
  {
    "name": " Dr. Aayed ",
    "type": " Opthalmology ",
    "rating": 4.9,
    "goodReviews": 12.2,
    "totalScore": 75.2,
    "satisfaction": 84.2,
    "isfavourite": true,
    "image": "assets/images/doctor4.jpg",
    "description": "A doctor can be found in several settings",
  }
];
